- name: install base fonts and Chinese fonts
  apt: 
    name: [libxrender1,libxext6,xfonts-75dpi,xfonts-base,ttf-wqy-zenhei,ttf-wqy-microhei]
    force: yes

- name: Install wkhtmltopdf
  apt:
    deb: "{{wkhtmltopdf_ubuntu_download}}"
