---
#1 install wkhtmltopdf by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

#2 configure wkhtmltopdf
- name: wkhtmltox symbolic link
  file:
    src: /usr/local/bin/{{item}}
    dest: /usr/bin/{{item}}
    state: link
  with_items:
    - wkhtmltopdf
    - wkhtmltoimage


